[build-system]
requires = ["setuptools>=61.0","mysql"]
build-backend = "setuptools.build_meta"

[project]
name = "history-loader"
version = "0.1"
authors = [
]
description = ""
readme = ""
requires-python = ">=3.7"
classifiers = [
]
dependencies = [
    "pyyaml"
]

[project.urls]

